stages:
  - DEV
  

PROD update app:
  stage: DEV
  tags: [dev-new-denginadom1]
  only:
    refs:
      - main
  when: manual
  script:
    - yarn install
    - yarn build


PROD update app and restart:
  stage: DEV
  tags: [dev-new-denginadom1]
  only:
    refs:
      - main
  when: manual
  script:
    - pm2 stop ecosystem.config.js 
    - yarn install
    - yarn build
    - pm2 start ecosystem.config.js -i 2

PROD restart app:
  stage: DEV
  tags: [dev-new-denginadom1]
  only:
    refs:
      - main
  when: manual
  script:
    - pm2 stop ecosystem.config.js 
    - yarn install --ignore-engines
    - yarn build
    - pm2 start ecosystem.config.js -i 2

PROD yarn upgrade packages:
  stage: DEV
  tags: [dev-new-denginadom1]
  only:
    refs:
      - main
  when: manual
  script:
    - pm2 stop ecosystem.config.js 
    - yarn upgrade
    - pm2 start ecosystem.config.js -i 2


